use_frameworks!
platform :ios, '9.0'

target 'NotificationBanner_Example' do
  pod 'NotificationBannerSwift', :path => '../'
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']

  target 'NotificationBanner_Tests' do
    inherit! :search_paths


  end
end
