use_frameworks!
platform :ios, '9.0'

target 'NotificationBanner_Example' do
  pod 'NotificationBannerSwift', :path => '../'
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']

  target 'NotificationBanner_Tests' do
    inherit! :search_paths


  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        swift4_projects = ['MarqueeLabel']
        if swift4_projects.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        end
    end
end
