use_frameworks!

target 'NotificationBanner_Example' do
  pod 'NotificationBanner', :path => '../'
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']

  target 'NotificationBanner_Tests' do
    inherit! :search_paths

    
  end
end
